version: 0.1

environment_variables:
            
phases:
  install:
    commands:
  pre_build:
    commands:
  build:
    commands:
  post_build:
    commands:
artifacts:
  files:
  discard-paths: yes